Lab 5
viclown/web pull request #5
Opened 2022-12-04 18:35 UTC by viclown

2022-12-04 20:04 UTC, viclown commented
![image](https://user-images.githubusercontent.com/76227700/205512836-77c38eaa-31dc-4621-99cc-f02d8aa2da7f.png)

2022-12-05 10:50 UTC, BakasaRus requested changes
Надо бы разобраться с DOM и починить вёрстку на новой страничке

2022-12-05 10:50 UTC, BakasaRus commented on JS/action.js
> +            </div>
Вот это лучше вынести в HTML в тег `<template/>`

2022-12-05 10:50 UTC, BakasaRus commented on JS/action.js
> +        </div>
См. выше

2022-12-12 20:43 UTC, merged